---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener-extension-image-rewriter
  labels:
    app.kubernetes.io/name: gardener-extension-image-rewriter
    helm.sh/chart: gardener-extension-image-rewriter
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - extensions
  - extensions/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  resourceNames:
  - {{ include "name" . }}
  verbs:
  - update
  - patch
- apiGroups:
  - resources.gardener.cloud
  resources:
  - managedresources
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - resources.gardener.cloud
  resources:
  - managedresources
  resourceNames:
  - extension-image-rewriter-shoot-webhooks
  verbs:
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - list
  - watch
