---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardener-extension-image-rewriter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-image-rewriter
    helm.sh/chart: gardener-extension-image-rewriter
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
