kind: Configuration
apiVersion: config.image-rewriter.extensions.gardener.cloud/v1alpha1
containerd:
- upstream: "k8s.io"
  server: "https://k8s.io"
  hosts:
  - url: "https://mirror.registry.gardener.cloud"
    provider: "local"
    regions: ["north"]
- upstream: "europe-docker.pkg.dev"
  server: "https://europe-docker.pkg.dev"
  hosts:
  - url: "https://registry.gardener.cloud/v2/south"
    provider: "local"
    regions: ["south"]
  - url: "https://registry.gardener.cloud/v2/west"
    provider: "local"
    regions: ["west"]
  - url: "https://registry.gardener.cloud/v2/east"
    provider: "local"
    regions: ["east"]
overwrites:
- source:
    prefix: "europe-docker.pkg.dev/gardener-project"
  targets:
  - prefix: "north.registry.gardener.cloud/gardener-project"
    provider: "local"
    regions: ["north"]
  - prefix: "south.registry.gardener.cloud/gardener-project"
    provider: "local"
    regions: ["south"]
  - prefix: "west.registry.gardener.cloud/gardener-project"
    provider: "local"
    regions: ["west"]
  - prefix: "east.registry.gardener.cloud/gardener-project"
    provider: "local"
    regions: ["east"]
