image:
  # ref: europe-docker.pkg.dev/gardener-project/public/gardener/extensions/image-rewriter:latest
  repository: europe-docker.pkg.dev/gardener-project/public/gardener/extensions/image-rewriter
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

# settings for metrics, e.g. scraping by seed-prometheus
metrics:
  enableScraping: true
  # default metrics endpoint in controller-runtime
  port: 8080

resources:
  requests:
    cpu: 50m
    memory: 64Mi
vpa:
  enabled: true
  resourcePolicy:
    minAllowed:
      memory: 32Mi
    controlledValues: RequestsOnly
  updatePolicy:
    updateMode: "Auto"

healthPort: 8081

controllers:
  concurrentSyncs: 5
  heartbeat: 
    renewIntervalSeconds: 30 
  ignoreOperationAnnotation: false

webhookConfig:
  servicePort: 443
  serverPort: 10250

gardener:
  version: ""

#overwrites:
#- source:
#    prefix: "eu.gcr.io/gardener-project/gardener/"
#  targets:
#  - prefix: "eu.aws.amazon.com/gardener-project/gardener/"
#    provider: "local"
#    regions: ["north]

#containerd:
#- upstream: "k8s.io"
#  server: "https://k8s.io"
#  hosts:
#  - url: "https://mirror.registry.gardener.cloud"
#    provider: "local"
#    regions: ["north"]
